name: nexacore
description: Common UI used for other projects.
version: 0.0.1
homepage: https://github.com/rondey84/NexaCore
repository: https://github.com/rondey84/NexaCore
issue_tracker: https://github.com/rondey84/NexaCore/issues
topics:
  - ui
  - widgets
  - helpers

environment:
  sdk: ">=3.1.4 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  flutter_screenutil: ^5.9.0
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
